### ISSUE TITLE
about pyrenderer

### ISSUE THREAD

**Issue by zhuyazhi** [wenbowen123/iros20-6d-pose-tracking#20]
sorry to bother you.
1.  once I use pyrender, 
self.renderer = Renderer([obj_path],self.cam_K,dataset_info['camera']['height'],dataset_info['camera']['width'])

this error occurs:

Traceback (most recent call last):
  File "/home/tiger/anaconda3/envs/se3/lib/python3.7/site-packages/pyrender/platforms/pyglet_platform.py", line 39, in init_context
    width=1, height=1)
  File "/home/tiger/anaconda3/envs/se3/lib/python3.7/site-packages/pyglet/window/xlib/__init__.py", line 165, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/tiger/anaconda3/envs/se3/lib/python3.7/site-packages/pyglet/window/__init__.py", line 588, in __init__
    config = screen.get_best_config(config)
  File "/home/tiger/anaconda3/envs/se3/lib/python3.7/site-packages/pyglet/canvas/base.py", line 194, in get_best_config
    raise window.NoSuchConfigException()
pyglet.window.NoSuchConfigException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "produce_train_pair_data.py", line 269, in <module>
    completeBlenderYcbDR()
  File "produce_train_pair_data.py", line 220, in completeBlenderYcbDR
    producer = ProducerPurturb(dataset_info)
  File "produce_train_pair_data.py", line 86, in __init__
    self.renderer = Renderer([obj_path],self.cam_K,dataset_info['camera']['height'],dataset_info['camera']['width'])
  File "/opt/tiger/zyz_6d_pose/iros20-6d-pose-tracking/offscreen_renderer.py", line 69, in __init__
    self.r = pyrender.OffscreenRenderer(self.W, self.H)
  File "/home/tiger/anaconda3/envs/se3/lib/python3.7/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/home/tiger/anaconda3/envs/se3/lib/python3.7/site-packages/pyrender/offscreen.py", line 149, in _create
    self._platform.init_context()
  File "/home/tiger/anaconda3/envs/se3/lib/python3.7/site-packages/pyrender/platforms/pyglet_platform.py", line 45, in init_context
    'internal error message was "{}"'.format(e)
ValueError: Failed to initialize Pyglet window with an OpenGL >= 3+ context. If you're logged in via SSH, ensure that you're running your script with vglrun (i.e. VirtualGL). The internal error message was ""

could you give me some advice?

**Comment by gonalo99** [comment]
Hello! Do you mind sharing how you solved this problem?

**Comment by week0425** [comment]
Hello, I also meet this error. Can you share the solution? Thank you!

**Comment by gonalo99** [comment]
Hi! I solved this error by changing `-e "DISPLAY=unix:0.0"` to `-e "DISPLAY=$DISPLAY"` in the `run_container.sh` file inside the `docker` folder, you can try to see if it works for you.

**Comment by week0425** [comment]
> Hi! I solved this error by changing `-e "DISPLAY=unix:0.0"` to `-e "DISPLAY=$DISPLAY"` in the `run_container.sh` file inside the `docker` folder, you can try to see if it works for you.

Thank you for your advise, but it dosen't work for me.

**Comment by assia855** [comment]
Hi @week0425 and @wenbowen123  I have the same error and the solution of @zhuyazhi didn't work for me. can you suggest to me another solution please.

**Comment by wenbowen123** [comment]
@week0425 @assia855 are you running on a headless server?

**Comment by assia855** [comment]
@wenbowen123 I'm running the docker
