### ISSUE TITLE
  File "/home/posetrack/blender_dataset_generator.py", line 303, in generate     assert len(texture_files)>0 AssertionError

### ISSUE THREAD

**Issue by monajalal** [wenbowen123/iros20-6d-pose-tracking#75]
I tried running the following script and got this error. Can you please guide how to fix it? Thanks a lot.

```
root@ada:/home/posetrack# wget https://archive.cs.rutgers.edu/pracsys/se3_tracknet/1.blend
--2024-02-19 16:47:15--  https://archive.cs.rutgers.edu/pracsys/se3_tracknet/1.blend
Resolving archive.cs.rutgers.edu (archive.cs.rutgers.edu)... 128.6.4.51, 2620:0:d60:ac04::33
Connecting to archive.cs.rutgers.edu (archive.cs.rutgers.edu)|128.6.4.51|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 263868336 (252M) [application/octet-stream]
Saving to: '1.blend'

1.blend                                            100%[================================================================================================================>] 251.64M  2.79MB/s    in 77s     

2024-02-19 16:48:37 (3.27 MB/s) - '1.blend' saved [263868336/263868336]

root@ada:/home/posetrack# ls
1.blend    Utils.py                      config.yml            datasets.py  eval_ycbineoat.py   object_models          predict_ros.py              se3_tracknet.py  vispy_renderer.py
LICENSE    blender_dataset_generator.py  data_augmentation.py  docker       media               offscreen_renderer.py  problems.py                 train.py
README.md  blender_main.py               dataset_info.yml      eval_ycb.py  network_modules.py  predict.py             produce_train_pair_data.py  train.sh
root@ada:/home/posetrack# vi blender_main.py
root@ada:/home/posetrack# python blender_main.py 
('code_dir: ', '/home/posetrack')
/blender-2.79b-linux-glibc219-x86_64/blender /home/posetrack/1.blend -b -P /home/posetrack/blender_dataset_generator.py 
AL lib: (EE) ALCplaybackOSS_open: Could not open /dev/dsp: No such file or directory
found bundled python: /blender-2.79b-linux-glibc219-x86_64/2.79/python
Read blend: /home/posetrack/1.blend
Color management: scene view "sRGB OETF" not found, setting default "Default".
Color management: sequencer colorspace "sRGB OETF" not found, will use default instead.
Color management: image colorspace "sRGB OETF" not found, will use default instead.
Color management: image colorspace "sRGB OETF" not found, will use default instead.
Color management: image colorspace "sRGB OETF" not found, will use default instead.
Color management: image colorspace "sRGB OETF" not found, will use default instead.
Color management: image colorspace "sRGB OETF" not found, will use default instead.
Color management: image colorspace "sRGB OETF" not found, will use default instead.
Color management: image colorspace "sRGB OETF" not found, will use default instead.
Color management: image colorspace "sRGB OETF" not found, will use default instead.
Color management: image colorspace "sRGB OETF" not found, will use default instead.
Color management: image colorspace "sRGB OETF" not found, will use default instead.
Color management: image colorspace "sRGB OETF" not found, will use default instead.
Color management: image colorspace "sRGB OETF" not found, will use default instead.
Color management: image colorspace "sRGB OETF" not found, will use default instead.
Color management: image colorspace "sRGB OETF" not found, will use default instead.
Color management: image colorspace "sRGB OETF" not found, will use default instead.
Color management: image colorspace "sRGB OETF" not found, will use default instead.
Color management: image colorspace "sRGB OETF" not found, will use default instead.
Color management: image colorspace "sRGB OETF" not found, will use default instead.
Color management: image colorspace "sRGB OETF" not found, will use default instead.
Color management: image colorspace "sRGB OETF" not found, will use default instead.
Color management: image colorspace "sRGB OETF" not found, will use default instead.
Color management: image colorspace "sRGB OETF" not found, will use default instead.
Color management: image colorspace "sRGB OETF" not found, will use default instead.
Color management: image colorspace "sRGB OETF" not found, will use default instead.
Color management: image colorspace "sRGB OETF" not found, will use default instead.
/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/transformations.py:1998: UserWarning: No module named '_transformations'
  warnings.warn(str(exc))
Using: /home/posetrack/dataset_info.yml
K:
 [[1.066778e+03 0.000000e+00 3.129869e+02]
 [0.000000e+00 1.067487e+03 2.413109e+02]
 [0.000000e+00 0.000000e+00 1.000000e+00]]
Collecting texture files...
Traceback (most recent call last):
  File "/home/posetrack/blender_dataset_generator.py", line 396, in <module>
    generate()
  File "/home/posetrack/blender_dataset_generator.py", line 303, in generate
    assert len(texture_files)>0
AssertionError

Blender quit
root@ada:/home/posetrack# 

```

I am using your docker file for running the script. Also, there was a typo in the script that I have fixed it below:
```
  #blender_start_file = f'{code_dir}/1.blend'
  blender_start_file = code_dir + '/1.blend'
```

^^ error before fix:

```
root@ada:/home/posetrack# python blender_main.py 
  File "blender_main.py", line 47
    blender_start_file = f'{code_dir}/1.blend'
                                             ^
SyntaxError: invalid syntax
```

**Comment by DanieleBertagnoli** [comment]
Hi, I have the same issue. I think that is because if you look at the folders specified in `dataset_info.yml` in the docker container, they are empty. Did you put random images there to solve it or what?
